name: Mirroring

on: [push, pull]

env:

  MIRROR_URL: "https://github.com/EpitechPromo2026/B-DOP-200-COT-2-1-chocolatine-egnonnonhoun.gbahoungba.git"
  EXECUTABLES: "pushswap"

jobs:
  name: check_repository_cleanliness:
  runs-on: ubuntu-latest
  steps:                                              
  - uses: actions/checkout@v3
  - run: |
          useless_files=($(find . -name '*.o' -o -name '*.a' -o \
          -name '*.so' -o -name '*gcno' -o -name '*.gcda' -o -name '#*#' \
          -o -name '*~' -o -iname "*chocolat*" -o -path *tmp/*))
          for i in ${useless_files[@]}; do
            echo "::error file=$i,line=1,endLine=1,title=Unwanted file detected::$i"
          done
          fi
          
run_test:
    runs-on: ubuntu-latest
    needs: check_compilation
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make test_run
        timeout-minutes: 2

pushmirror:
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}